from importCSV import load_image

talent_lib = {
    'opportunist': {
        'Hide': {'requirement': 10, 'activate': 5, 'cooldown': 500, 'unlocked': False,
                 'description': 'Hide. Character is invisible if does not move.',
                 'img': load_image('./graphics/talents/0.png')},
        'Dirty Tricks': {'requirement': 35, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                         'description': 'Dirty Tricks. Improves critical hit chance by 10%.',
                         'img': load_image('./graphics/talents/2.png')},
        'Streetwise': {'requirement': 60, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                       'description': 'Streetwise. Adds dialog options, improves rewards and allows theft.',
                       'img': load_image('./graphics/talents/4.png')},
        'Mercenary Commander': {'requirement': 85, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                                'description': 'Mercenary Commander. Allows deployment of mercenary troops for gold.',
                                'img': load_image('./graphics/talents/merc_commander.png')},
        'Pick Locks': {'requirement': 20, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                       'description': 'Pick Locks. Character can open locked chests.',
                       'img': load_image('./graphics/talents/lockpick.png')},
        'Duelist': {'requirement': 45, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                    'description': 'Duelist. Gives a 10% chance to restore action if attacked.',
                    'img': load_image('./graphics/talents/duel.png')},
        'Use Devices': {'requirement': 70, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                        'description': 'Use Devices. Can disarm, set traps and use other mechanical contraptions.',
                        'img': load_image('./graphics/talents/mechanism.png')},
        'Deadly Aim': {'requirement': 100, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                       'description': 'Deadly Aim. All critical hits inflict death effect instead of bleeding.',
                       'img': load_image('./graphics/talents/7.png')},
    },
    'warlord': {
        'Quartermaster': {'requirement': 10, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                          'description': 'Quartermaster. Deploying troops costs 20% less.',
                          'img': load_image('./graphics/talents/1.png')},
        'Improve Infantry': {'requirement': 35, 'activate': 5, 'cooldown': 500, 'unlocked': False,
                              'description': 'Improve Infantry. Infantry receives an attack bonus.',
                              'img': load_image('./graphics/talents/infantry.png')},
        'Improve Archers': {'requirement': 60, 'activate': 5, 'cooldown': 500, 'unlocked': False,
                             'description': 'Improve Archers. Archers receive an attack bonus.',
                             'img': load_image('./graphics/talents/4.png')},
        'Improve Cavalry': {'requirement': 70, 'activate': 5, 'cooldown': 500, 'unlocked': False,
                             'description': 'Improve Cavalry. Cavalry receives an attack bonus.',
                             'img': load_image('./graphics/talents/cavalry.png')},
        'Advanced Warfare': {'requirement': 20, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                             'description': 'Advanced Warfare. Improves critical hit chance by 10%.',
                             'img': load_image('./graphics/talents/warfare.png')},
        'Rally Troops': {'requirement': 45, 'activate': 5, 'cooldown': 500, 'unlocked': False,
                         'description': 'Rally Troops. Troops under this command restore their armor.',
                         'img': load_image('./graphics/talents/rallytroops.png')},
        'Master Warfare': {'requirement': 85, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                           'description': 'Master Warfare. Gives 10% chance to hit all enemies in range.',
                           'img': load_image('./graphics/talents/7.png')},
        'Tactics': {'requirement': 100, 'activate': 10, 'cooldown': 500, 'unlocked': False,
                    'description': 'Tactics. Troops under this command can survive a deadly strike.',
                    'img': load_image('./graphics/talents/tactics.png')},
    },
    'scholar': {
        'Educated': {'requirement': 10, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                     'description': 'Educated. Party gains 20% more experience.', 'img': load_image('./graphics/talents/educated.png')},
        'Advanced Alchemy': {'requirement': 35, 'activate': 5, 'cooldown': 500, 'unlocked': False,
                             'description': 'Advanced Alchemy. Gives access to liquid fire, poison flask and acid.', 'img': load_image('./graphics/talents/2.png')},
        'Siege Machines': {'requirement': 60, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                            'description': 'Siege Machines. Reduces deployment requirements by 20%.',
                            'img': load_image('./graphics/talents/siege.png')},
        'Master Alchemist': {'requirement': 85, 'activate': 10, 'cooldown': 500, 'unlocked': False,
                             'description': 'Master Alchemist. Gives access to feral toxin, fire and smoke bomb.', 'img': load_image('./graphics/talents/6.png')},
        'Medicine': {'requirement': 20, 'activate': 10, 'cooldown': 500, 'unlocked': False,
                     'description': 'Medicine. Restores health to injured troops.', 'img': load_image('./graphics/talents/medicine.png')},
        'Theology': {'requirement': 45, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                     'description': 'this is a scholar talent', 'img': load_image('./graphics/talents/prayer.png')},
        'Divination': {'requirement': 70, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                       'description': 'this is a scholar talent',
                       'img': load_image('./graphics/talents/0.png')},
        'Planar Protector': {'requirement': 100, 'activate': 25, 'cooldown': 500, 'unlocked': False,
                             'description': 'Planar Protector. Summons a powerful divine being from another plane.', 'img': load_image('./graphics/talents/guardian.png')},
    },
    'wanderer': {
        'Respite': {'requirement': 10, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                    'description': 'this is a wanderer talent', 'img': load_image('./graphics/talents/respite.png')},
        'Tame Animal': {'requirement': 35, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                         'description': 'this is a wanderer talent',
                         'img': load_image('./graphics/talents/tame_animal.png')},
        'Second Wind': {'requirement': 60, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                        'description': 'this is a wanderer talent',
                        'img': load_image('./graphics/talents/second_wind.png')},
        'Tame Beast': {'requirement': 85, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                       'description': 'this is a wanderer talent', 'img': load_image('./graphics/talents/beast.png')},
        'Advanced Archery': {'requirement': 20, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                             'description': 'this is a wanderer talent',
                             'img': load_image('./graphics/talents/archery.png')},
        'Cartographer': {'requirement': 45, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                         'description': 'this is a wanderer talent', 'img': load_image('./graphics/talents/map.png')},
        'Ambush': {'requirement': 70, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                   'description': 'this is a wanderer talent', 'img': load_image('./graphics/talents/ambush.png')},
        'Master Archer': {'requirement': 100, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                          'description': 'this is a wanderer talent',
                          'img': load_image('./graphics/talents/archery2.png')},
    },
    'mystic': {
        'Elemental Shield': {'requirement': 10, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                             'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/elementalshield.png')},
        'Fireball': {'requirement': 35, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                     'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/fireball.png')},
        'Flame Fog': {'requirement': 60, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                      'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/firefog.png')},
        'Meteor Rain': {'requirement': 85, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                        'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/meteor.png')},
        'Fire Arrows': {'requirement': 20, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                        'description': 'this is a mystic talent',
                        'img': load_image('./graphics/talents/fire_arrow.png')},
        'Overcharge': {'requirement': 45, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                       'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/overcharge.png')},
        'Summon Elemental': {'requirement': 70, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                             'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/elemental.png')},
        'Dragon Form': {'requirement': 100, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                        'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/dragonform.png')},
    },
    'witch': {
        'Arcane Defence': {'requirement': 10, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                           'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/0.png')},
        'Concentration': {'requirement': 35, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                          'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/focus.png')},
        'Frozen Star': {'requirement': 60, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                        'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/4.png')},
        'Storm': {'requirement': 85, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                  'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/6.png')},
        'Ice Shard': {'requirement': 20, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                      'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/1.png')},
        'Energy Blast': {'requirement': 45, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                      'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/3.png')},
        'Living Armor': {'requirement': 70, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                         'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/5.png')},
        'Crystal Twins': {'requirement': 100, 'activate': 0, 'cooldown': 500, 'unlocked': False,
                         'description': 'this is a mystic talent', 'img': load_image('./graphics/talents/7.png')},
    },
}

